# Basic Information 
title: Vaibhav Gusain
position: PhD student
affiliation: Trinity college dublin
affiliation_link: https://www.scss.tcd.ie/
email: gusainv (at) tcd.ie

# Search Engine Optimization (SEO)
keywords: vaibhav gusain, gusain vaibhav, vaibhavgusain, gusainvaibhav, vaibhav, gusain
canonical: https://www.scss.tcd.ie/~gusainv/
description: Vaibhav gusain is a Phd student at School of computer science and statistics in Trinity college dublin. His research lies in data privacy, machine learning, and Large language models.


# The option is used to show the last update time.
enable_last_update: false

# Links
google_scholar: https://scholar.google.com/citations?user=TihNNNYAAAAJ
#cv_link: https://files.yliu.me/Yaoyao_Liu_Curriculum_Vitae.pdf
github_link: https://github.com/vaibhav0195
linkedin:  https://www.linkedin.com/in/vaibhav-gusain/
#twitter: https://twitter.com/YaoyaoLiu1/

# Images 
avatar: mypic.jpg
#favicon: ./assets/img/favicon.png
#favicon_dark: ./assets/img/favicon-dark.png

# Footnotes
#footnote: Feel free to use my website's source code.
#footnote_link: https://github.com/yaoyao-liu/minimal-light

# Analytics
# Please remove the following lines about analytics services if you fork my project. 
# Otherwise, the analytics information of your website will be recorded to my ClustrMaps accounts.
#clustrmaps_id: l3lesztPwCz-uXlzFI1Lt9SB3Ctz-pBQuMdYqnD0Ul8

# The following files will be removed from the generated website.
exclude:
  - Gemfile
  - Gemfile.lock
  - README.md
  - LICENSE
  - CNAME
